version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pdf-generator-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1at52fu89mnk3"
s3_prefix = "pdf-generator-lambda"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
